[project]
name = "inctxt"
version = "0.0.1"
authors = [
  { name = "X", email = "X@X.com" },
]
dependencies = [
  "torch",
  "transformers",
  "datasets",
  "evaluate",      # rouge metric
  "mypy",
  "python-dotenv",
  "rouge_score",
  "joblib",
  "seaborn",
]
